Exception in udp_receiver, init: Address already in use (Bind failed)
Exception in thread "main" java.lang.RuntimeException: java.net.BindException: Address already in use (Bind failed)
	at cs451.Udp_receiver.<init>(Udp_receiver.java:31)
	at cs451.Receiver.<init>(Receiver.java:28)
	at cs451.Main.initialize(Main.java:124)
	at cs451.Main.main(Main.java:76)
Caused by: java.net.BindException: Address already in use (Bind failed)
	at java.base/java.net.PlainDatagramSocketImpl.bind0(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:131)
	at java.base/java.net.DatagramSocket.bind(DatagramSocket.java:394)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:244)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:301)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:273)
	at cs451.Udp_receiver.<init>(Udp_receiver.java:28)
	... 3 more
